### ISSUE TITLE
Multiple repos with different policies

### ISSUE THREAD

**Issue by lukeledet** [moritzheiber/terraform-aws-oidc-github-actions-module#71]
Hi I'm using this module to hookup github actions for CI with terraform. I would like to reuse the openid connector to also give a separate repository access to ECR but with permissions limited to only pushing images into a private ECR repo. Is this something I can currently do or will it require changes to the module? I started to send a PR adding the openid connector to the outputs so it can be used separately but figured I would ask first.

**Comment by moritzheiber** [comment]
That depends entirely on your security model. Technically, any repository tied to the connector is allowed to assume any role you create using the module. Whatever policies you associate with these roles is up to you (the documentation for this repository contains a 1-1 example for a role and set of permissions; that can be any number of roles and/or permissions though).

So what you are asking for is just a matter of having the second pipeline assume a different role with specifically tailored permissions for ECR. I believe you should even be further able to limit the assumption to just that one repository using IAM conditions, but I haven’t tried that yet.

There is no PR necessary to achieve the desired behavior as I understand it :)

**Comment by moritzheiber** [comment]
@lukeledet Unless there are more questions I'll close this issue for now. Please feel free to either file a new issue or have me re-open this one if there's more context I can support you with :blush:
